name: cricketteammanager
services:
  - name: web
    type: web
    git:
      repository: github.com/sriram3k/cricketteammanager
      branch: main
    build:
      buildpack: nodejs
      build_command: npm install && npm run build && npm run db:push
      run_command: npm run start
    instance_type: free
    regions:
      - was
    ports:
      - port: 5000
        protocol: http
    routes:
      - path: /
        port: 5000
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: DATABASE_URL
        secret: DATABASE_URL
      - key: SESSION_SECRET
        secret: SESSION_SECRET
