import { useMemo, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { api, ApiError } from '../../src/api';
import { useDebounced, useLoader } from '../../src/hooks';
import { useDialog } from '../../src/dialog';
import { Badge, Button, Card, EmptyState, ErrorBanner, Field, Loading, Row, SearchBar, Segmented } from '../../src/components/ui';
import { colors, formatDate, formatSGD, radius, spacing, type } from '../../src/theme';
import type { BulkPreview, BulkResult, PaymentMode, PendingPlayerRow } from '../../src/types';

type Step = 'select' | 'confirm';
type Sort = 'amount' | 'name' | 'oldest';
type Mode = 'FULL' | 'AMOUNT';

/**
 * Feature 2 — the bulk flow. Select players, choose full-settlement or a
 * per-player amount, then review a summary generated by the server before
 * anything is written.
 */
export default function BulkPaymentScreen() {
  const router = useRouter();
  const dialog = useDialog();
  const [step, setStep] = useState<Step>('select');
  const [search, setSearch] = useState('');
  const [sort, setSort] = useState<Sort>('amount');
  const [payMode, setPayMode] = useState<Mode>('FULL');
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [amounts, setAmounts] = useState<Record<string, string>>({});
  const [method, setMethod] = useState<PaymentMode>('PAYNOW');
  const [reference, setReference] = useState('');
  const [preview, setPreview] = useState<BulkPreview | null>(null);
  const [banner, setBanner] = useState<string | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);

  const debounced = useDebounced(search);
  const pending = useLoader(
    () => api.get<PendingPlayerRow[]>('/api/payments/pending', { search: debounced, sort }),
    [debounced, sort],
  );

  const rows = pending.data ?? [];
  const allSelected = rows.length > 0 && rows.every((r) => selected.has(r.playerId));

  const selectedTotal = useMemo(() => {
    let cents = 0;
    for (const row of rows) {
      if (!selected.has(row.playerId)) continue;
      if (payMode === 'FULL') cents += row.totalPendingCents;
      else {
        const typed = Number(amounts[row.playerId]);
        if (Number.isFinite(typed)) cents += Math.round(typed * 100);
      }
    }
    return cents / 100;
  }, [rows, selected, amounts, payMode]);

  function toggle(playerId: string) {
    const next = new Set(selected);
    if (next.has(playerId)) next.delete(playerId);
    else next.add(playerId);
    setSelected(next);
    setErrors({});
  }

  function toggleAll() {
    setSelected(allSelected ? new Set() : new Set(rows.map((r) => r.playerId)));
    setErrors({});
  }

  function buildTargets() {
    return [...selected].map((playerId) => ({
      playerId,
      ...(payMode === 'AMOUNT' ? { amount: (amounts[playerId] ?? '').trim() } : {}),
    }));
  }

  function validateAmounts(): boolean {
    if (payMode === 'FULL') return true;
    const next: Record<string, string> = {};
    for (const playerId of selected) {
      const raw = (amounts[playerId] ?? '').trim();
      if (!/^\d+(\.\d{1,2})?$/.test(raw) || Number(raw) <= 0) {
        next[playerId] = 'Enter an amount greater than zero';
      }
    }
    setErrors(next);
    return Object.keys(next).length === 0;
  }

  async function goToConfirm() {
    setBanner(null);
    if (selected.size === 0) {
      setBanner('Select at least one player.');
      return;
    }
    if (!validateAmounts()) return;

    setBusy(true);
    try {
      setPreview(await api.post<BulkPreview>('/api/payments/bulk/preview', { targets: buildTargets() }));
      setStep('confirm');
    } catch (err) {
      if (err instanceof ApiError) {
        setErrors(err.fieldErrors);
        setBanner(err.message);
      } else {
        setBanner('Could not build the summary. Check your connection and try again.');
      }
    } finally {
      setBusy(false);
    }
  }

  async function commit() {
    setBanner(null);
    setBusy(true);
    try {
      const res = await api.post<BulkResult>('/api/payments/bulk', {
        targets: buildTargets(),
        mode: method,
        reference: reference.trim() || undefined,
      });
      await dialog.notify({
        title: 'Payments recorded',
        message: `${res.message}\n\nYou can undo this until ${formatDate(res.undoAvailableUntil)}.`,
        confirmLabel: 'Done',
      });
      router.back();
    } catch (err) {
      if (err instanceof ApiError) {
        setErrors(err.fieldErrors);
        setBanner(err.message);
      } else {
        setBanner('Could not record the payments. Nothing was saved — please try again.');
      }
      setStep('select');
    } finally {
      setBusy(false);
    }
  }

  if (step === 'confirm' && preview) {
    return (
      <View style={styles.screen}>
        <FlatList
          contentContainerStyle={styles.content}
          data={preview.rows}
          keyExtractor={(r) => r.playerId}
          ListHeaderComponent={
            <View>
              <ErrorBanner message={banner} />
              <Card>
                <Text style={type.label}>ABOUT TO RECORD</Text>
                <Text style={styles.bigMoney}>{formatSGD(preview.totalAmount)}</Text>
                <Text style={type.caption}>
                  {preview.playerCount} player{preview.playerCount === 1 ? '' : 's'} ·{' '}
                  {preview.totalChargesCleared} charge
                  {preview.totalChargesCleared === 1 ? '' : 's'} cleared ·{' '}
                  {preview.playersFullySettled} fully settled
                </Text>
                {Number(preview.totalUnallocated) > 0 ? (
                  <Text style={[type.caption, { color: colors.warning, marginTop: spacing.xs }]}>
                    {formatSGD(preview.totalUnallocated)} exceeds what is owed and will not be
                    allocated.
                  </Text>
                ) : null}
                <Text style={[type.caption, { marginTop: spacing.sm }]}>
                  Recorded as {method.replace('_', ' ')}
                  {reference.trim() ? ` · ref ${reference.trim()}` : ''}
                </Text>
              </Card>
              <Text style={[type.heading, { marginBottom: spacing.sm }]}>Per player</Text>
            </View>
          }
          renderItem={({ item }) => (
            <Card style={{ padding: spacing.md }}>
              <Row style={{ justifyContent: 'space-between' }}>
                <Text style={type.body}>{item.playerName}</Text>
                <Text style={type.money}>{formatSGD(item.amountToPay)}</Text>
              </Row>
              <Text style={[type.caption, { marginTop: 2 }]}>
                {formatSGD(item.pendingBefore)} → {formatSGD(item.pendingAfter)} ·{' '}
                {item.chargesCleared} cleared
                {item.chargesPartiallyPaid > 0 ? `, ${item.chargesPartiallyPaid} part-paid` : ''}
              </Text>
              {item.warning ? (
                <Text style={[type.caption, { color: colors.warning, marginTop: 2 }]}>
                  {item.warning}
                </Text>
              ) : null}
              {item.fullySettled ? (
                <View style={{ marginTop: spacing.sm }}>
                  <Badge label="FULLY SETTLED" tone="success" />
                </View>
              ) : null}
            </Card>
          )}
        />
        <View style={styles.footer}>
          <Row style={{ gap: spacing.sm }}>
            <Button
              label="Back"
              variant="secondary"
              onPress={() => setStep('select')}
              style={{ flex: 1 }}
            />
            <Button
              label="Confirm and record"
              onPress={() => void commit()}
              loading={busy}
              style={{ flex: 2 }}
            />
          </Row>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.screen}>
      <FlatList
        contentContainerStyle={styles.content}
        data={rows}
        keyExtractor={(r) => r.playerId}
        refreshControl={
          <RefreshControl
            refreshing={pending.refreshing}
            onRefresh={pending.refresh}
            tintColor={colors.primary}
          />
        }
        ListHeaderComponent={
          <View>
            <ErrorBanner message={banner ?? pending.error} />

            <Card>
              <Text style={[type.label, { marginBottom: spacing.sm }]}>HOW MUCH</Text>
              <Segmented
                value={payMode}
                onChange={setPayMode}
                options={[
                  { value: 'FULL', label: 'Full pending' },
                  { value: 'AMOUNT', label: 'Amount each' },
                ]}
              />
              <Text style={[type.caption, { marginTop: spacing.sm }]}>
                {payMode === 'FULL'
                  ? 'Settles whatever each selected player currently owes.'
                  : 'Each amount is applied oldest charge first; a shortfall leaves the charge part-paid.'}
              </Text>

              <View style={{ height: spacing.lg }} />

              <Text style={[type.label, { marginBottom: spacing.sm }]}>PAYMENT MODE</Text>
              <Segmented
                value={method}
                onChange={setMethod}
                options={[
                  { value: 'PAYNOW', label: 'PayNow' },
                  { value: 'BANK_TRANSFER', label: 'Transfer' },
                  { value: 'CASH', label: 'Cash' },
                ]}
              />
              <View style={{ height: spacing.md }} />
              <Field
                label="Reference (optional)"
                value={reference}
                onChangeText={setReference}
                error={errors.reference}
                placeholder="e.g. collection on 12 Mar"
              />
            </Card>

            <SearchBar value={search} onChangeText={setSearch} placeholder="Search players…" />
            <View style={{ marginTop: spacing.sm }}>
              <Segmented
                value={sort}
                onChange={setSort}
                options={[
                  { value: 'amount', label: 'Owing' },
                  { value: 'name', label: 'Name' },
                  { value: 'oldest', label: 'Oldest' },
                ]}
              />
            </View>

            <Pressable onPress={toggleAll} style={styles.selectAll}>
              <Text style={[type.label, { color: colors.primary }]}>
                {allSelected ? 'CLEAR SELECTION' : 'SELECT ALL'}
              </Text>
            </Pressable>
          </View>
        }
        renderItem={({ item }) => {
          const on = selected.has(item.playerId);
          return (
            <View style={[styles.playerRow, on && styles.playerRowSelected]}>
              <Pressable
                onPress={() => toggle(item.playerId)}
                accessibilityRole="checkbox"
                accessibilityState={{ checked: on }}
                style={styles.playerTap}
              >
                <View style={[styles.check, on && styles.checkOn]}>
                  <Text style={styles.checkMark}>{on ? '✓' : ''}</Text>
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={type.body}>{item.name}</Text>
                  <Text style={type.caption}>
                    {item.chargeCount} charge{item.chargeCount === 1 ? '' : 's'} · oldest{' '}
                    {formatDate(item.oldestChargeDate)}
                  </Text>
                </View>
                <Text style={[type.money, { color: colors.danger }]}>
                  {formatSGD(item.totalPending)}
                </Text>
              </Pressable>

              {on && payMode === 'AMOUNT' ? (
                <View style={styles.amountRow}>
                  <Text style={type.caption}>Pay now</Text>
                  <TextInput
                    value={amounts[item.playerId] ?? ''}
                    onChangeText={(v) => {
                      setAmounts((a) => ({ ...a, [item.playerId]: v }));
                      setErrors((e) => ({ ...e, [item.playerId]: '' }));
                    }}
                    keyboardType="decimal-pad"
                    placeholder={item.totalPending}
                    placeholderTextColor={colors.textMuted}
                    style={[styles.amountInput, !!errors[item.playerId] && styles.amountInputError]}
                  />
                </View>
              ) : null}
              {on && errors[item.playerId] ? (
                <Text style={styles.error}>{errors[item.playerId]}</Text>
              ) : null}
            </View>
          );
        }}
        ListEmptyComponent={
          pending.loading ? <Loading /> : <EmptyState title="Nobody has an outstanding balance" />
        }
      />

      <View style={styles.footer}>
        <Row style={{ justifyContent: 'space-between', marginBottom: spacing.sm }}>
          <Text style={type.body}>
            {selected.size} selected
          </Text>
          <Text style={type.money}>{formatSGD(selectedTotal.toFixed(2))}</Text>
        </Row>
        <Button
          label="Review summary"
          onPress={() => void goToConfirm()}
          loading={busy}
          disabled={selected.size === 0}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { padding: spacing.lg, paddingBottom: spacing.xxl },
  bigMoney: { fontSize: 32, fontWeight: '800', color: colors.primary, marginVertical: spacing.xs },
  selectAll: { paddingVertical: spacing.md },
  playerRow: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.sm,
    padding: spacing.md,
  },
  playerRowSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  playerTap: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  check: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  checkOn: { backgroundColor: colors.primary, borderColor: colors.primary },
  checkMark: { color: '#fff', fontSize: 14, fontWeight: '800' },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  amountInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    minWidth: 120,
    textAlign: 'right',
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
    backgroundColor: colors.surface,
  },
  amountInputError: { borderColor: colors.danger, backgroundColor: colors.dangerSoft },
  error: { color: colors.danger, fontSize: 12, fontWeight: '500', marginTop: spacing.xs },
  footer: {
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
});
