name: cricketiq
region: nyc

services:
  - name: web
    github:
      repo: sriram3k/cricketteammanager
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm run db:push && npm start
    instance_size_slug: basic-xs
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: APP_URL
        scope: RUN_TIME
        type: SECRET
      - key: SENDGRID_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FROM_EMAIL
        scope: RUN_TIME
        type: SECRET

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb
    num_nodes: 1
